### PR TITLE
REST API UI v1.1

### PR DESCRIPTION
**Pull request by kernelsndrs**
This is mostly a transfer of code from PR #850, with a refactor from bower to webpack and few small changes related to bootstrap4.

**TODO**
move to partials, integrate ajax updating
integrate --api flag which sets auto stat dumping and prevents toggle
explore best representation for multiple running zenbot instances

_this pull request resubmitted after a failed rebase._

### CODE REVIEW

**Comment by JensvdHeydt** [comment]
@DeviaVir Is anything blocking this PR to be merged?

**Review by DeviaVir — APPROVED** [review]
Let's see it in the wild, thanks for contributing! :+1:

**Comment by mkuendig** [comment]
I get this build error related to webpack:

Step #0: > rm -rf node_modules/forex.analytics/.git && webpack -p
Step #0: 
Step #0: [91mNo configuration file found and no output filename configured via CLI option.
Step #0: [0m[91mA configuration file could be named 'webpack.config.js' in the current directory.
Step #0: [0m[91mUse --help to display the CLI options.
Step #0: [0m[91mnpm[0m[91m [0m[91mERR![0m[91m code ELIFECYCLE

Have tried multiple things to troubleshoot. No luck. When I remove webpack -p from package.json the build completes. Any hints?

Strangely, when I start the container without webpack -p as postinstall and do it after the container is started, npx webpack -p runs successfully.

**Comment by DeviaVir** [comment]
@mkuendig pull latest, this should be fixed now

**Pull request merged**
