### PR TITLE
Implement version check

### LINKED ISSUE #259: Implement version check
Make sure people are at the very least running node 6 or exit.

### PR DESCRIPTION
**Pull request by DeviaVir**
Fixes #259

### CODE REVIEW

**Comment by DeviaVir** [comment]
@carlos8f is ^ 6.0.0 the version we want to support, or is that a higher/lower scope?

**Comment by egorbenko** [comment]
can we use `process.version` instead of adding another package?

**Comment by DeviaVir** [comment]
@egorbenko this actually uses `process.version`, but a standard version package (semver), which is already installed by other packages as a dependency, is used to do the compare.
https://github.com/carlos8f/zenbot/pull/274/files#diff-aa5e31044d72d2583b98d7a040daca84R9

(hence also no update to `package-lock.json`)

**Comment by DeviaVir** [comment]
this is an issue that keeps popping up in the discord channel, merging this in now to prevent those..

**Pull request merged**
