### PR TITLE
xmpp for trading alarms

### PR DESCRIPTION
**Pull request by piedrogenius**
Added optional account set-up and buy/sell alarms with XMPP. Needs simple-xmpp and 2 XMPP server accounts: one for sending the trader messages and one for receiving them.

Considering two way functionality to disable/reenable live trading while running

### CODE REVIEW

**Comment by tuxitor** [comment]
Wouldn't it be better to add a generic plugin interface to engine.js than hardwire the xmpp protocol into it. There are a lot of messaging apps out there, and everyone have thir own preferences. WebSockets comes to mind for building a messaging interface. It opens the possibility for all kinds of extensions

**Comment by piedrogenius** [comment]
Completely right.

I will look into abstracting the messaging protocol and controlling the bot through (xmpp) messaging.

Those are my first steps with node.js and I was amazed on how easy it was to integrate xmpp. Any other coding challenge is beyond my capacity for the moment.

**Comment by tuxitor** [comment]
The topic is interesting, and I have some ideas around this to share. My nick on Discord is *tuxador* if you wan to discuss. https://discord.gg/HcPhKX

**Comment by tuxitor** [comment]
@piedrogenius 
See if you can hook xmpp into this:
https://github.com/tuxitor/zenbot/blob/master/docs/Zentalk.md
You can take advantage of websocket by using this program as a base:
https://github.com/tuxitor/zenbot/blob/master/zenout.sh
Output is plain JSON with the trade data.

**Review by DeviaVir — APPROVED** [review]

**Comment by DeviaVir** [comment]
@tuxitor I fully agree with your comments here, but I'm also a firm believer in building blocks, the existence of this will make it easier for people to start using XMPP *today* and future contributors to easily extend this.

Merging. Thanks for the work and time @piedrogenius! :+1:

**Comment by tuxitor** [comment]
@DeviaVir 
I agree with you to a certain extent, but still think this deserves a comment. It is obviously easier to get a head start by entering the credentials in the config file. But the concept of hardcoding xmpp functions into the engine code means functions scattered around the code, and extending this at the end means a lot of code pollution.

To the contrary, the zentalk concept has a lot more potential for extension without changing an additional single line if code in the engine program. This means a lot for maintainability of the code because all extended functionality is done outside the zenbot code.

As of today zentalk have both mail and xmpp reporting, and have had for quite a while.

Besides that zentalk has access to most of the zebot data in a form (JSON) which is ideal for use by other programs (still without the need for changing anyting zenbot)

From the interactive zentalk program a lot of data is already available in JSON form. These are options, balance, product, period, strat, quote, status and trades availabe through a get request. some options are even possible to change during a live run. The period object is ideal for extracting candles, to name one. Only imagination limits the use. And still without changing anything in the zenbot code. This is modular design, and the documentation is quite decent

https://github.com/tuxitor/zenbot/blob/zentalk/docs/Zentalk.md

I think it is worth looking into it again.

**Comment by DeviaVir** [comment]
@tuxitor by no means am I saying that these overwrites any and all other efforts, I'm only saying I'm not principally against adding a change just because there is a better way (that hasn't been picked up by anyone so far). The ticket to implement something better is still open, for example.

**Pull request merged**
