### PR TITLE
Updated the bitfinex product settings for XMR/BTC

### PR DESCRIPTION
**Pull request by mxaddict**
Updated the bitfinex product settings for XMR/BTC

### CODE REVIEW

**Comment by nedievas** [comment]
I think there is no need to update separate pairs every time Bitfinex changes minimal order. You can pull these by executing `update-producs.sh`. Increment is a pain in the ***, and these should be updated to everyone's personal favor. I get better ROI when trading LTC-BTC with increment 0.0001, worse when increment is 0.0000001.

**Comment by mxaddict** [comment]
@nedievas 
Hmmm, you think that a larger increment is better?

Do you mind sharing your base conf for doing LTC-BTC, I want to tune my XMR-BTC trading and make some OK profit, then I can invest more into my bot's balance :)

**Comment by DeviaVir** [comment]
I agree with @nedievas here, if anyone would PR a latest `update-products.sh` result I'll accept it.

**Comment by mxaddict** [comment]
Created PR #744 as suggested/requested :)

**Pull request closed without merging**
