### PR TITLE
Bittrex Exchange Hybrid Backfilling / Error handling / Products update

### PR DESCRIPTION
**Pull request by station384**
Address issue #1218 making URL request error a recoverable error.
Correct generation of bittrex products.json.  min size is now taken into account.
Addresses Issues #499,#816, and my own personal annoyance with its inability to back-fill.

Back-filling is accomplished by using the candle api and the
marketHistory

Candle api
1 minute interval
max history of about 10 days
mapping to
size: total volume traded in 1 min
price: closing price for the 1 min period
side: forced as sell as there is no way to tell since this is a sum of
both buy and sells in the 1 minute period

marketHistory
is directly mapped but only has the last 100 trades

### CODE REVIEW

**Comment by station384** [comment]
This does accomplish the backfill,  but it does save "imaginary" trades, each one of the imaginary ones is the sum of all the trades for 1m or what ever the gap is from the previous one.   

All imaginary trades buy/sell is guessed.

I figure the buy/sell for this doesn't really matter for what were looking for here, what were really after is the price and the time of that price, and the volume traded so we can calculate velocity.

any calculations that take into the account number of past trades of buy/sell orders a may be incorrect.

**Comment by station384** [comment]
Done poking at it.  
Still unsure what to mark the buy/sell as on the long term back-fills, but i'm guessing using this logic.
If the price is higher than the last price, then there should have been more buys to push the closing price higher.  therefore mark the trade as a buy.

The confusion comes from the perspective.   looking at the marker trend this is the correct view.  looking at as a trader, this is incorrect, because if the price is higher.  I would have sold.

**Comment by station384** [comment]
Okay really done poking at it.

**Comment by station384** [comment]
@DeviaVir, I'm Done with bittrex.  on to getting hitbtc to work.

**Comment by XarImoR** [comment]
The only error i'm getting now on bittrex is this:

/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:233
        market: joinProduct(opts.product_id)
                                 ^
TypeError: Cannot read property 'product_id' of undefined
    at Object.getQuote (/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:233:34)
    at Timeout._onTimeout (/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:42:24)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

Any idea to solve this?
@station384:
By the way... really good job repairing Bittrex

Parameters :
./zenbot.sh trade bittrex.WINGS-ETH --strategy ta_macd ---buy_pct 10 --buy_max_amt 0.33 --order_type maker

(error with other coins as well -- ADT-ETH/DGB-ETH/STRAT-ETH/WAVES-ETH/SNT-ETH/FUN-ETH )

**Comment by station384** [comment]
what are the parameters you are sending in so I can try and reproduce this error.  Its one that I havn't seen yet.

**Comment by station384** [comment]
They only way I was able to reproduce it was to delete the item out of the products.json.
You may try updating it by executing extensions/exchanges/bittrex/update-products.sh

note:  you need to be in the extensions/exchanges/bittrex/ directory when executing so it will save the products.json in that directory.

**Comment by station384** [comment]
@XarImoR  I finally got this error to reproduce while the coin combo was in the products list.  It only seems to be on the the ETH market,  I am still trying to figure out what the error is caused by, but is taking awhile as it happens only under rare conditions for me.

**Comment by XarImoR** [comment]
Unfortunately, I still get this 3 Error's on Bittrex with the Prameters above..

**1**
/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:233
        market: joinProduct(opts.product_id)
                                 ^

TypeError: Cannot read property 'product_id' of undefined
    at Object.getQuote (/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:233:34)
    at Timeout._onTimeout (/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:42:24)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)


**2**
/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:258
          bid: data.result.Bid,
                           ^

TypeError: Cannot read property 'Bid' of null
    at /home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:258:28
    at Request._callback (/home/ubuntu/zenbot-watcher/node_modules/node-bittrex-api/node.bittrex.api.js:143:11)
    at Request.self.callback (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


**3**
APIKEY_INVALID
/home/ubuntu/zenbot-watcher/commands/trade.js:512
                throw new Error('Error during syncing balance. Please check your API-Key')

Error: Error during syncing balance. Please check your API-Key
    at /home/ubuntu/zenbot-watcher/commands/trade.js:512:23
    at /home/ubuntu/zenbot-watcher/lib/engine.js:281:11
    at /home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:257:9
    at Request._callback (/home/ubuntu/zenbot-watcher/node_modules/node-bittrex-api/node.bittrex.api.js:143:11)
    at Request.self.callback (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:1060:10)
    at Request.emit (events.js:214:7)                                                                                                                                                                                            [0/1849]9]
    at Request.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by XarImoR** [comment]
Unfortunately, I got this 3 Error's today on Bittrex with the Prameters above on many Pairs ( on ETH market)..

**1**
/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:233
        market: joinProduct(opts.product_id)
                                 ^

TypeError: Cannot read property 'product_id' of undefined
    at Object.getQuote (/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:233:34)
    at Timeout._onTimeout (/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:42:24)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)


**2**
/home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:258
          bid: data.result.Bid,
                           ^

TypeError: Cannot read property 'Bid' of null
    at /home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:258:28
    at Request._callback (/home/ubuntu/zenbot-watcher/node_modules/node-bittrex-api/node.bittrex.api.js:143:11)
    at Request.self.callback (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


**3**
APIKEY_INVALID
/home/ubuntu/zenbot-watcher/commands/trade.js:512
                throw new Error('Error during syncing balance. Please check your API-Key')

Error: Error during syncing balance. Please check your API-Key
    at /home/ubuntu/zenbot-watcher/commands/trade.js:512:23
    at /home/ubuntu/zenbot-watcher/lib/engine.js:281:11
    at /home/ubuntu/zenbot-watcher/extensions/exchanges/bittrex/exchange.js:257:9
    at Request._callback (/home/ubuntu/zenbot-watcher/node_modules/node-bittrex-api/node.bittrex.api.js:143:11)
    at Request.self.callback (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:1060:10)
    at Request.emit (events.js:214:7)                                                                                                                                                                                            [0/1849]9]
    at Request.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/zenbot-watcher/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

I think the Bittrex-Exchange has today some performance issues as well

**Comment by station384** [comment]
I have received  
"Cannot read property 'product_id' of undefined" 2x on ETH market,  havn't seen it on the BTC or USDT.  So far I have not been able to track it down the cause due to the infrequency of the occurrence.

"Error during syncing balance. Please check your API-Key" -- this I still get, but is treated now as a recoverable error,  it shouldn't crash the program. If your version is crashing on this, you my not have some of the updates I included in this pull after the first post.

I have not received
"Cannot read property 'Bid' of null", this looks like during a buy or a sell operation, but unsure

I suspect these are all related to cloudfare interfering, and they are all the same error just showing up as different because of where it is happening in the code.   All of them can be caused by the API not responding for one reason or other.  1-2 is when the api doesn't respond with the data we think it should have. 

1 and 2 has to do with error handing.    I just need to catch it, or log it some how when it happens  (need the JSON of the error object that is returned, do figure out conditions)
I've just run out of time to implement the code to catch this right now. 

3. I can't do anything about.  it will happen, it is there API not accepting the keys because of some reason or another.  The only thing I can do is retry the command after a few seconds, which I have implemented.

**Comment by station384** [comment]
I've added extra logging to any errors that occur when calling the API. Try and get to the bottom of this errors.

**Comment by station384** [comment]
Do not post an unedited debug result.  It will contain API key as it seems it is returned by the API results.   Going to close down this pull till I figure out these errors.

**Comment by XarImoR** [comment]
thanks for the warning...but this is a text copy from a other machine...but i will delete the comment

**Pull request closed without merging**
