### PR TITLE
Hitbtc working exchange

### PR DESCRIPTION
**Pull request by station384**
Reworked hitbtc exchange.  Now works.  Short term tested.
buy/sell/cancel.

### CODE REVIEW

**Comment by station384** [comment]
Note:  Backfill does NOT retrieve any meaningful results.   This is a limit of the exchange.   I will work later on creating a hybrid solution like I did with bittrex using a combination of Candle data, and market data.   My first goal here was to get the exchange to trade.  

If you are going to be doing any backtesting/sim trading on this exchange,  you will need to paper trade, or trade using the noop strategy  so it will not buy or sell anything and use a 1m period_length.  Do this for at least 24 hours to get a decent dataset to use for sim trading

**Comment by station384** [comment]
Doing more long term testing.   just got another error.

**Comment by station384** [comment]
9hrs so far.  no bugs or crashes.   +1% profit :)
Think I may have this exchange locked down.

**Review by DeviaVir — APPROVED** [review]
:+1: great work

**Comment by vtnplus** [comment]
not working friend:
run to ---------------------------------------- STARTING LIVE TRADING ---------------------------------------- and nothing , nothing :(

**Comment by station384** [comment]
What are the parameters you are using to execute zenbot?

I ask this as I am currently trading on hitbtc on markets xrp-usdt and omg-eth,
they have both been trading for about 2 days, and both have had restarts due to better trade strategies found buy darwin processing.

I would like to try and reproduce the issue you are having.

I am currently using UNSTABLE branch.

**Comment by vtnplus** [comment]
this is problem friend 
Press  l  to list available commands.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Pull request merged**
