### PR TITLE
Visual dashboard for REST API

### PR DESCRIPTION
**Pull request by ArnaudRitti**
Dashboard for zenbot

It work on tablet, desktop and mobile.
On mobile you can add it to home screen and it works like a app.

screenshot_20171212-231925

fireshot 1

### CODE REVIEW

**Review by DeviaVir — APPROVED** [review]
Impressive amount of work! The only feedback I have is that people are most likely going to ask how to access the dashboard you created, could you add that to the README.md?

**Review by darland — APPROVED** [review]
Looks great.

**Comment by JensvdHeydt** [comment]
This looks very good! Just a little thing: This PR also changes files like neural/strategy.js. Why?

**Review by storm1er — APPROVED** [review]
For me it's a great YES :

 - We should avoid bower implementation as the developpers officialy said stop : https://github.com/bower/bower/issues/2298 (going on webpack ?)
 - It feels like the whole project is not commented enough, this PR is a plus on this point ^^
 - Indentation lovers (like me) will hate you some days :joy_cat: 
 - Is jQuery shouldn't be included through package.json instead of bower ? (just asking)
 

Love your work =D

**Review by albabosh — COMMENTED** [review]
ReferenceError: minimist is not defined, but it is really present:
tradeops@47148:~/zenbot$ npm list minimist
zenbot4@4.0.5 /home/tradeops/zenbot
+-- eslint@4.12.1
| `-- mkdirp@0.5.1
|   `-- minimist@0.0.8
+-- minimist@1.2.0
`-- simple-xmpp@1.3.0
  `-- node-xmpp-client@3.2.0
    `-- minimist@1.2.0  deduped

tradeops@47148:~/zenbot$

**Comment by nunofgs** [comment]
Will this support multiple instances of zenbot? (ie: if the UI always fetches from the mongo database, it can display stats for multiple active trading pairs)

**Comment by sergejostir** [comment]
Why does this remove talib for example? Isn't it about adding UI, not messing with core zenbot?

**Review by tiagosiebler — CHANGES_REQUESTED** [review]
@ArnaudRitti can you re-do this PR without the extra changes? I think this is on hold since it changes a ton of other files, including core files such as trade.js, in a way that'll affect others unintentionally. 

Would love to see this PR merged, but I don't think it'll happen until those changes are cleaned out and this PR only changes the minimum needed.

**Comment by pursehouse** [comment]
screenshots look nice.. how do we actually get this running?

**Comment by nibzo1** [comment]
This looks awesome, I would love to see this in zenbot. I've wanted to do this for a long time.  

Any help required to get this over the line?

**Comment by phenixtai** [comment]
So Nice, Great work, when we can use it ?
Very good idea !

**Comment by kernelsndrs** [comment]
Duplicate of #1015 which was merged into unstable

**Pull request closed without merging**
