### PR TITLE
Made genetic_backtester more robust

### PR DESCRIPTION
**Pull request by theDiverDK**
Fixed the following things:

Sort the best strategies would failed if one of the stategies has undefined as fitness

Added code a few places to handle values being undefined, before the code could crash.

Did code cleanup, to more follow the official coding standard (if not okay, please tell me)

### CODE REVIEW

**Review by DeviaVir — APPROVED** [review]
:+1: lgtm

**Comment by phatwila** [comment]
@theDiverDK Not sure if this was intended, but its no longer outputting the current generations best result command to run.
image

**Comment by theDiverDK** [comment]
Hi Phatwila

Nope that was not the intend, thanks for reporting it.

Working on another feature, after that ill fix it.

/Søren

**Comment by theDiverDK** [comment]
I have fixed it, in a pull request i just send

**Pull request merged**
