### PR TITLE
GDAX: cancel_after

### PR DESCRIPTION
**Pull request by DeviaVir**
Superseding https://github.com/carlos8f/zenbot/pull/340

Please review:
- [x] @crubb 
- [x] @nedievas

### CODE REVIEW

**Comment by nedievas** [comment]
Hi. It would be nice to use similar option for Bitfinex by adding manual cancel to replicate this GDAX order parameter, wouldn't?

**Review by crubb — APPROVED** [review]

**Comment by nedievas** [comment]
Reading [GDAX API docs](https://docs.gdax.com/#place-a-new-order) I found that we miss another option for 'cancel_after' to work as intended: 
> Time in force
> Time in force policies provide guarantees about the lifetime of an order. There are four policies: good till canceled GTC, good till time GTT, immediate or cancel IOC, and fill or kill FOK.
> GTT Good till time orders remain open on the book until canceled or the allotted cancel_after is depleted on the matching engine. GTT orders are guaranteed to cancel before any other order is processed after the cancel_after timestamp which is returned by the API. A day is considered 24 hours.

Please confirm that this enhancement is really working before merge.

**Comment by DeviaVir** [comment]
@nedievas good point, added.

**Comment by DeviaVir** [comment]
Seems to work. Merging.

**Pull request merged**
