### PR TITLE
Bitfinex WS: Attempt to fix reconnect issues on "API Key invalid" errors

### PR DESCRIPTION
**Pull request by crubb**
Hey,

potential fix for #480.

@nedievas, @tjoin: Please test!

Cheers,
crubb

### CODE REVIEW

**Comment by tjoin** [comment]
Now I'm testing it, will let you know if I found something,
Thanks

**Review by nedievas — APPROVED** [review]
Looks fixed.

**Comment by cirrusdex** [comment]
testing it right now

**Review by nedievas — APPROVED** [review]
Merge.

**Comment by procmail** [comment]
I suspect the error below is because I opened 5 instances too fast.

I'm getting:

```
fetching pre-roll data:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (429)
    at ClientRequest._req.on (/home/eric/zenbot/node_modules/ws/lib/WebSocket.js:656:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:547:20)
```

**Comment by procmail** [comment]
Orders on bitfinex are not being placed. Despite waiting for hours and seeing quite a few buy and sell signals, I don't see corresponding orders on bitfinex.

**Comment by crubb** [comment]
Just seeing buy or sell doesn’t mean it’s actually placing an order - That would be „buying“ and „selling“. Anyway, that’s working fine for a number of people. Please also run zenbot with —debug enabled.

**Comment by crubb** [comment]
Not a problem of the zenbot Bitfinex websockets implementation. HTTP 429 is „Too many requests“.

**Review by nedievas — APPROVED** [review]

**Comment by crubb** [comment]
@DeviaVir A little merge, pretty please? ;)

**Comment by nedievas** [comment]
Stable fixes. Merge.

**Review by DeviaVir — APPROVED** [review]

**Pull request merged**
