### PR TITLE
Neural, Trendline, StdDev Strategies

### PR DESCRIPTION
**Pull request by ghost**
Hello! Let me know if anything in this needs to be updated for the PR.
Most of the strats will require backfilling or will receive an error.

Neural will take some time to tune, but everything you need to tune it is there.

http://cs.stanford.edu/people/karpathy/convnetjs/demo/regression.html

For a demo of the regression learning neural code.

### CODE REVIEW

**Comment by sniper7kills** [comment]
I pulled your repo and am getting the following error:

```
ubuntu@ip-172-31-12-176:~/zenbot-ai$ ./zenbot.sh trade --paper --reset_profit --stratagy neural
/home/ubuntu/zenbot-ai/extensions/strategies/neural/strategy.js:21
      if (s.lookback[s.options.start_trigger]) {
           ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/zenbot-ai/extensions/strategies/neural/_codemap.js:4:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /home/ubuntu/zenbot-ai/boot.js:25:19
    at Array.forEach (<anonymous>)
    at /home/ubuntu/zenbot-ai/boot.js:24:15
    at f (/home/ubuntu/zenbot-ai/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/ubuntu/zenbot-ai/node_modules/glob/glob.js:151:7)
```

**Comment by ghost** [comment]
I should be done with the neural strategy now, please pull and let me know if any errors since it's a lot of code. 
Neural (takes a ton of processing power): 
Neural running

**Comment by evseevnn-zz** [comment]
@TheRoboKitten 
I trying get profit from this strategy but it look like impossible. Can you show any configuration for get profit like example ETH USD

**Comment by ghost** [comment]
Going to clean up code some

**Comment by mxaddict** [comment]
@Gr1dd, how did you get the neural strat profitable? I tried running in simulations and seems to loose, I'm currently running it in --paper mode, are you using defaults in the screenshot that you show above from 11 days ago?

**Pull request closed without merging**
