### PR TITLE
WIP kraken support

### PR DESCRIPTION
**Pull request by grigio**

### CODE REVIEW

**Comment by grigio** [comment]
Minimal support #9 
- it calls the public api to get BTCUSD rates

I'm not sure if Kraken supports &limit parameter

**Comment by grigio** [comment]
@carlos8f I see teh data processing, but I don't see the graph on localhost.. I get "no data"

**Comment by carlos8f** [comment]
hmm, I'll test it out

**Comment by grigio** [comment]
The backfill time is always the same

**Comment by carlos8f** [comment]
fixed it in master, the `since` param is actually microtime, not a standard timestamp

**Comment by grigio** [comment]
Thanks!

**Pull request merged**
