### PR TITLE
Docker: extend README slightly

### PR DESCRIPTION
**Pull request by DeviaVir**
Giving a handy reference to people that exclusively use docker.

### CODE REVIEW

**Comment by felipecaldas** [comment]
oh wow, champion!

**Comment by egorbenko** [comment]
@DeviaVir add --rm flag to remove container on exit, otherwise you end up with bunch of dangling containers that aren't doing anything

**Comment by DeviaVir** [comment]
@egorbenko good point; I usually run spotify's `docker-gc` every now and then, but this is nice and tidy.

**Comment by egorbenko** [comment]
@DeviaVir i'll let @carlos8f review and merge, looks good to me. thank you for contributing!

**Comment by carlos8f** [comment]
ok cool 👍

**Pull request merged**
