### PR TITLE
FIxing kraken product update and product list

### PR DESCRIPTION
**Pull request by cmroche**
Adds a check for the known broken currencies

### CODE REVIEW

**Comment by cmroche** [comment]
Fixes bug https://github.com/carlos8f/zenbot/issues/427

**Comment by timstoop** [comment]
Tested this locally, but it only fixes part of the problem. With this patch applied and running `balance kraken.BCH-EUR`, it does not recognise the EUR I have in my account.

**Comment by cmroche** [comment]
Ok, thanks for the feedback. I should be able to devise a solution.

**Comment by cmroche** [comment]
@timstoop Try applying the change again, should work now.

**Comment by timstoop** [comment]
balance works, backfill works and trade --paper works! Great stuff!

**Review by DeviaVir — APPROVED** [review]

**Pull request merged**
