### PR TITLE
missing dep "eyes": "^0.1.8"

### PR DESCRIPTION
**Pull request by grigio**

### CODE REVIEW

**Review by DeviaVir — CHANGES_REQUESTED** [review]
You will also need to include an updated `package-lock.json`:

```
rm -rf package-lock.json
npm i
git add package-lock.json
git commit
```

**Comment by grigio** [comment]
Ok I'll update it. I noticed I had to install manually another dependency for the bitfinex support

**Comment by grigio** [comment]
I'm not sure it is needed I tried to clone a new zenbot at it seems to work without it

**Comment by cmroche** [comment]
This is also resolved in PR #576 The problem isn't that eyes is missing from the package.json, but that the package-lock.json wasn't updated after the package "cliff" was added to the project. Eyes is included indirectly from this package, updating the package lock resolves issues with both "cliff" and "eyes".

**Pull request closed without merging**
