### PR TITLE
More technical indicators + textbelt notifier

### PR DESCRIPTION
**Pull request by yura505**
Technical indicators:
- ADX+DI
- Trend Continuation Factor, by M.H. Pee
- Linear Regression Curve
- Variable Moving Average, by Tushar S. Chande

Bonus - textbelt.com notifier.

### CODE REVIEW

**Comment by evseevnn-zz** [comment]
@yura505 
Thank for your work.
Please, update readme.md

**Comment by evseevnn-zz** [comment]
@yura505 Sorry, i mean need wrote in readme.md about params of new strategies. Because i don't know how use it without that.

**Comment by yura505** [comment]
@evseevnn There aren’t strategies, just some technical indicators. Anyone can use them to write strategies. These indicators are not my inventions, but I use them to trade bitcoin. If you interesting in these indicators, I can share with you some links, however all of them are googable by indicator name. Just google “linear regression curve” or “variable moving average”.

**Comment by evseevnn-zz** [comment]
@yura505 Sorry me, you right. Apparently, I was affected by a hard working day.

**Review by DeviaVir — APPROVED** [review]
Awesome stuff, merging this in and let's see what strategies can roll out of this.

**Pull request merged**
