### PR TITLE
network ip

### PR DESCRIPTION
**Pull request by nedievas**
Completed network ip commit from @mountaindrifter

### CODE REVIEW

**Comment by johanatan** [comment]
Were the changes to `plugins/bitfinex/exchange.json` accidental? What do they have to do with `network ip` ?

**Comment by s-ftf** [comment]
Changes to `plugins/bitfinex/exchange.json` and `plugins/bitfinex/_codemap.js` is not required for the ip address. Should just be `plugins/server/_codemap.js`, though the `plugins/server/action.js` looks reasonable too. Original PR was [105](https://github.com/carlos8f/zenbot/pull/105), can we merge these or shall we just close 105?

**Comment by s-ftf** [comment]
I suppose this should be moved into its own function somewhere...

**Comment by nedievas** [comment]
Sorry, my bad. Bitfinex changes goes to my Bitfinex branch. It's already there.

**Pull request closed without merging**
